### ISSUE TITLE
Handle re-breach of closed outlet

### ISSUE THREAD

**Issue by RegMeasures** [RegMeasures/HapuaModel#51]
Currently breaching always results in a straight channel but this is not realistic in the case of transitory closure. Need to:
- [x] preserve the location and size of the upstream end of the outlet channel during closure
- [x] Differentiate between reopening of old (upstream connected) outlet channel vs breach where there is no, or disconnected outlet channel.

**Comment by RegMeasures** [comment]
Still need to:
- [ ] Thoroughly test
- [ ] Update wiki

**Comment by RegMeasures** [comment]
inputs\HurunuiModelDevelop2.cnf

```
Time = 1900-01-20 21:54:30, MorDt = 960.0s
Preventing lagoonward truncation at X = 0.0m as it would result in a length 0 outlet channel
Preventing lagoonward truncation at X = 0.0m as it would result in a length 0 outlet channel
Velocity change in cross-section 54 equals -0.167728 (greater than WarnTol)
Velocity change in cross-section 53 equals -0.112370 (greater than WarnTol)
Truncating lagoon end of outlet channel (due to erosion) at X = 20.0m
Extending R end of lagoon via outletchannel to cliffline collision.
Schematisation requires removal of any remaining gravel between new lagoon and cliff-toe as part of extension
Preventing lagoonward truncation at X = 0.0m as it would result in a length 0 outlet channel
D:\Projects\HapuaModel\hapuamod\mor.py:601: RuntimeWarning: invalid value encountered in less
  if not Breach and np.any(CrestHeight < WaterLevel):
Velocity change in cross-section 53 equals 0.164378 (greater than WarnTol)
D:\Projects\HapuaModel\hapuamod\coast.py:134: RuntimeWarning: invalid value encountered in greater
  OverwashProp = ShoreZ[:,0] > (CrestWidth * PhysicalPars['BarRatSlope'] + PhysicalPars['BarRatInt'])
D:\Projects\HapuaModel\hapuamod\coast.py:144: RuntimeWarning: invalid value encountered in greater_equal
  assert np.all(CST_tot >= 0), 'Negative cross-shore transport in overtopping function!'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Projects\HapuaModel\hapuamod\__main__.py", line 45, in <module>
    main(ArgsIn.ModelConfigFile, ArgsIn.Overwrite)
  File "D:\Projects\HapuaModel\hapuamod\core.py", line 166, in main
    ShoreZ, PhysicalPars)
  File "D:\Projects\HapuaModel\hapuamod\coast.py", line 144, in overtopping
    assert np.all(CST_tot >= 0), 'Negative cross-shore transport in overtopping function!'
AssertionError: Negative cross-shore transport in overtopping function!
```

**Comment by RegMeasures** [comment]
inputs\HurunuiModelExtended.cnf

```
Time = 1900-05-08 21:14:30, MorDt = 1920.0s
Outlet channel elongated leftwards across transect line X = -340.0m
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Projects\HapuaModel\hapuamod\__main__.py", line 45, in <module>
    main(ArgsIn.ModelConfigFile, ArgsIn.Overwrite)
  File "D:\Projects\HapuaModel\hapuamod\core.py", line 176, in main
    PhysicalPars, TimePars, NumericalPars)
  File "D:\Projects\HapuaModel\hapuamod\mor.py", line 598, in updateMorphology
    CrestHeight[OutletPresent] = np.amax(ShoreZ[OutletPresent,[0,2]]) # transects with active or relic channels (could be diconnected)
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,)
```
