### ISSUE TITLE
Crash - size inconsistency between OnlineLagoon & ChanFlag[:-1]==1

### ISSUE THREAD

**Issue by RegMeasures** [RegMeasures/HapuaModel#52]
```Time = 2015-08-19 08:00:00
Time = 2015-08-19 09:00:00
Time = 2015-08-19 10:00:00
Outlet channel elongated rightwards across transect line x=-280.000000
Truncating lagoon end of outlet channel (due to erosion)
Outlet intersects lagoon at 1 transects - adding channel width into lagoon
Outlet closed
Velocity change in cross-section 87 equals -0.315295 (greater than WarnTol)
Velocity change in cross-section 66 equals 0.199807 (greater than WarnTol)
Velocity change in cross-section 87 equals -0.110328 (greater than WarnTol)
Outlet closed
Outlet closed
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Projects\HapuaModel\hapuamod\__main__.py", line 42, in <module>
    main(ArgsIn.ModelConfigFile, ArgsIn.Overwrite)
  File "C:\Projects\HapuaModel\hapuamod\core.py", line 160, in main
    ChanFlag, Closed)
  File "C:\Projects\HapuaModel\hapuamod\riv.py", line 550, in storeBedload
    LagoonBedload[OnlineLagoon] = Bedload[ChanFlag[:-1]==1]
ValueError: shape mismatch: value array of shape (70,) could not be broadcast to indexing result of shape (71,)```

**Comment by RegMeasures** [comment]
![image](https://user-images.githubusercontent.com/17330572/68540974-9b483a80-03fe-11ea-9bb2-808bca6008c0.png)
```Time = 2015-08-19 09:30:00
Time = 2015-08-19 09:45:00
Time = 2015-08-19 10:00:00
Outlet channel elongated rightwards across transect line x=-280.000000
Truncating lagoon end of outlet channel (due to erosion)
Outlet intersects lagoon at 1 transects - adding channel width into lagoon
Time = 2015-08-19 10:15:00
Outlet closed
Velocity change in cross-section 87 equals -0.319656 (greater than WarnTol)
Velocity change in cross-section 66 equals 0.202844 (greater than WarnTol)
Velocity change in cross-section 87 equals -0.111943 (greater than WarnTol)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Projects\HapuaModel\hapuamod\__main__.py", line 42, in <module>
    main(ArgsIn.ModelConfigFile, ArgsIn.Overwrite)
  File "C:\Projects\HapuaModel\hapuamod\core.py", line 160, in main
    ChanFlag, Closed)
  File "C:\Projects\HapuaModel\hapuamod\riv.py", line 550, in storeBedload
    LagoonBedload[OnlineLagoon] = Bedload[ChanFlag[:-1]==1]
ValueError: shape mismatch: value array of shape (70,) could not be broadcast to indexing result of shape (71,)```

**Comment by RegMeasures** [comment]
![image](https://user-images.githubusercontent.com/17330572/68541107-57563500-0400-11ea-9c1c-d018cdf0594a.png)
![image](https://user-images.githubusercontent.com/17330572/68541081-07776e00-0400-11ea-87a4-3ce2e582351c.png)


A lot going on in 2 timesteps... 
 * 10:00 to 10:15:
   * A. `Outlet channel elongated rightwards across transect line x=-280.000000`
   * B. `Truncating lagoon end of outlet channel (due to erosion)`
   * C. `Outlet intersects lagoon at 1 transects - adding channel width into lagoon`
* 10:15 to 10:30
   * D. `Outlet closed`

**Comment by RegMeasures** [comment]
Is the weird plotting problem in the map view of the last timestep a clue? or a separate bug?

**Comment by RegMeasures** [comment]
If outlet is angled L to R before all this change then why is the lagoon end of the channel not like this?
![image](https://user-images.githubusercontent.com/17330572/68541184-40fca900-0401-11ea-8044-8e21ae839578.png)

**Comment by RegMeasures** [comment]
I think this has most likely been fixed by other recent bug fixes so closing for now unless it reoccurs...
