### ISSUE TITLE
Divide by zero error caused by zero width lagoon?

### ISSUE THREAD

**Issue by RegMeasures** [RegMeasures/HapuaModel#65]
Crash during SimpleSynthetic.cnf simulation some time after 2003-09-29 14:01:00

>Preventing lagoonward truncation at X = -360.0 as it would result in a length 0 outlet channel
Preventing lagoonward truncation means outlet channel pushed into cliff at X = -360.0
Downstream end of outlet channel closed by longshore transport (EndX = -345.525780)
Velocity change in cross-section 68 equals -0.706480 (greater than WarnTol)
Velocity change in cross-section 68 equals 0.414213 (greater than WarnTol)
Velocity change in cross-section 68 equals 0.464025 (greater than WarnTol)
Velocity change in cross-section 68 equals 0.121496 (greater than WarnTol)
Velocity change in cross-section 68 equals -0.113124 (greater than WarnTol)
C:\Projects\HapuaModel\hapuamod\mor.py:84: RuntimeWarning: invalid value encountered in true_divide
  / ((ShoreY[OnlineLagoon, 3] - ShoreY[OnlineLagoon, 4]) * Dx))
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Downstream end of outlet channel closed by longshore transport (EndX = -345.525780)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Projects\HapuaModel\hapuamod\__main__.py", line 45, in <module>
    main(ArgsIn.ModelConfigFile, ArgsIn.Overwrite)
  File "C:\Projects\HapuaModel\hapuamod\core.py", line 105, in main
    NumericalPars['Dx'], PhysicalPars)
  File "C:\Projects\HapuaModel\hapuamod\riv.py", line 452, in assembleChannel
    assert not np.any(np.isnan(ChanElev)), 'NaN values in ChanElev after assembleChannel'
AssertionError: NaN values in ChanElev after assembleChannel

Maybe a solution would be to introduce a threshold (a few mm?) to use in comparisons for lagoon/barrier closure/collision if statements.

**Comment by RegMeasures** [comment]
On closer inspection I think what is happening is that the channel is closing then flow is routed through a zero width lagoon and gives a divide by zero error...

**Comment by RegMeasures** [comment]
I think this is an unintended result of what I did to fix a previous problem 05ac45b0aaa7b3d1f31120fd1bbdb48f8d8b0afe
