### ISSUE TITLE
Bug causing assert "Vol until level should not be negative" to be triggered

### ISSUE THREAD

**Issue by RegMeasures** [RegMeasures/HapuaModel#66]
```Velocity change in cross-section 71 equals 0.410493 (greater than WarnTol)
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Outlet channel closed by wave washover at X = -380.000000
Downstream end of outlet channel closed by longshore transport (EndX = -380.008465)
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Projects\HapuaModel\hapuamod\__main__.py", line 45, in <module>
    main(ArgsIn.ModelConfigFile, ArgsIn.Overwrite)
  File "C:\Projects\HapuaModel\hapuamod\core.py", line 163, in main
    PhysicalPars, TimePars, NumericalPars)
  File "C:\Projects\HapuaModel\hapuamod\mor.py", line 217, in updateMorphology
    assert np.all(VolUntilLevel > 0.0), "Vol until level should not be negative"
AssertionError: Vol until level should not be negative```

**Comment by RegMeasures** [comment]
It appears that closure of outlet end due to LST and last transect of outlet channel occurred in the same timestep right before this crash - not sure if this is related??

**Comment by RegMeasures** [comment]
Still needs testing before I close issue

**Comment by RegMeasures** [comment]
Seems to have fixed it :)
